//Mocks para la respuesta de la API

export const politiciansReponseMock = {
  total: 4095,
  items: [
    {
      _index: "test4",
      _id: "LV1SIYgBAQ4x-R5SpOa5",
      _score: 1,
      _source: {
        nombre: "Josep Manel Francés i Reig",
        partido: "Junts per Agres",
        partido_para_filtro: "Otros partidos",
        genero: "Hombre",
        cargo_para_filtro: "Alcalde",
        cargo: "Alcalde",
        institucion: "Ayuntamiento de Agres",
        ccaa: "Comunidad Valenciana",
        sueldobase_sueldo: 8467.36,
        otrasdietaseindemnizaciones_sueldo: 0,
        retribucionmensual: 604.81,
        retribucionanual: 8467.36,
        observaciones: "Dedicación Parcial",
      },
    },
    {
      _index: "test4",
      _id: "Ll1SIYgBAQ4x-R5SpOa5",
      _score: 1,
      _source: {
        nombre: "María Isabel Molina Vicens",
        partido: "Compromís",
        partido_para_filtro: "Compromís",
        genero: "Mujer",
        cargo_para_filtro: "Alcalde",
        cargo: "Alcaldesa",
        institucion: "Ayuntamiento de Alcalalí",
        ccaa: "Comunidad Valenciana",
        sueldobase_sueldo: 8833.26,
        otrasdietaseindemnizaciones_sueldo: 0,
        retribucionmensual: 630.95,
        retribucionanual: 8833.26,
        observaciones: "Dedicación Parcial",
      },
    },
    {
      _index: "test4",
      _id: "MF1SIYgBAQ4x-R5SpOa5",
      _score: 1,
      _source: {
        nombre: "Francisco Miguel Fenollar Iváñez",
        partido: "PSOE",
        partido_para_filtro: "PSOE",
        genero: "Hombre",
        cargo_para_filtro: "Alcalde",
        cargo: "Alcalde",
        institucion: "Ayuntamiento de Alcoleja",
        ccaa: "Comunidad Valenciana",
        sueldobase_sueldo: 0,
        otrasdietaseindemnizaciones_sueldo: 150,
        retribucionmensual: 10.71,
        retribucionanual: 150,
        observaciones: "Sin dedicación",
      },
    },
    {
      _index: "test4",
      _id: "MV1SIYgBAQ4x-R5SpOa5",
      _score: 1,
      _source: {
        nombre: "Antonio Alfonso Francés Pérez",
        partido: "PSOE",
        partido_para_filtro: "PSOE",
        genero: "Hombre",
        cargo_para_filtro: "Alcalde",
        cargo: "Alcalde",
        institucion: "Ayuntamiento de ALCOY/ALCOI",
        ccaa: "Comunidad Valenciana",
        sueldobase_sueldo: 57501.59,
        otrasdietaseindemnizaciones_sueldo: 0,
        retribucionmensual: 4107.26,
        retribucionanual: 57501.59,
        observaciones: "Dedicación Exclusiva",
      },
    },
    {
      _index: "test4",
      _id: "Ml1SIYgBAQ4x-R5SpOa5",
      _score: 1,
      _source: {
        nombre: "Vicente Arques Cortes",
        partido: "PSOE",
        partido_para_filtro: "PSOE",
        genero: "Hombre",
        cargo_para_filtro: "Alcalde",
        cargo: "Alcalde",
        institucion: "Ayuntamiento de L' Alfàs del Pi",
        ccaa: "Comunidad Valenciana",
        sueldobase_sueldo: 0,
        otrasdietaseindemnizaciones_sueldo: 11813,
        retribucionmensual: 843.79,
        retribucionanual: 11813,
        observaciones: "Sin dedicación",
      },
    },
  ],
};

export const politiciansErrorReponseMock = {
  error: "Internal error",
};
