name: Deploy Website

on:
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-node@v2.5.2
        with:
          node-version: 20
      - name: Install api dependencies and run tests
        run: |
          cd /api
          npm install --omit=dev
          npm run test
      - name: Install ui dependencies and run tests
        run: |
          cd /ui
          npm install --omit=dev
          npm run test
